name: ghh-runner

on:
  push:
    branches:
      - main

jobs:
  ngrok_tunnel:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          # Use SSH_PUBLIC_KEY secret
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519.pub
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Add User with Root Access
        run: |
          # Add a new user
          sudo useradd -m ghrunner -s /bin/bash
          echo 'ghrunner:ghrunner' | sudo chpasswd

          # Grant sudo (root) access to the ghrunner
          sudo usermod -aG sudo ghrunner

      - name: Display Hostname
        run: |
          hostname

      - name: Start NGROK tunnel
        run: |
          # Use NGROK_AUTHTOKEN secret
          docker run --net=host -e NGROK_AUTHTOKEN="$NGROK_AUTHTOKEN" ngrok/ngrok:latest tcp 22
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
